### ISSUE TITLE
id="menu" interferes with some pages

### ISSUE THREAD

**Issue by bennypowers** [PolymerElements/paper-swatch-picker#12]
### Description

Pages that already have a #menu break paper-swatch-picker.
If I import and  create a <paper-swatch-picker> on a page which already has a #menu, unexpected behaviour can occur with the swatch picker button.

**Comment by bennyp123** [comment]
consider this PR to fix: https://github.com/PolymerElements/paper-swatch-picker/pull/13

**Comment by notwaldorf** [comment]
Closing, #13 was merged
