### ISSUE TITLE
The style effects other elements like paper-item and paper-listbox

### ISSUE THREAD

**Issue by timcsy** [PolymerElements/paper-swatch-picker#21]
I imported the paper-swatch-picker, paper-item and paper-listbox together. However, it seems that my paper-item doesn't padding anymore. I guess the problem is due to the style setting of paper-swatch-picker. By the way, I'm using polymer 2.0, and maybe the problem can be fix to style the custom elements only and it will not affect other elements anymore.

**Comment by hitokiri8x** [comment]
seems like that 
`  paper-item {
        --paper-item: {
          margin: 0;
          padding: 0;
          min-height: 0;
        };`
got passed to external paper-items as well, afflicting listbox as well!

**Comment by jsilvermist** [comment]
@timcsy @hitokiri8x Which browser(s) did you notice this behavior in?

**Comment by hitokiri8x** [comment]
Firefox 54.04b13  ( beta ) and Chrome 58.0.3029.110 (64-bit)   
![screen](https://cloud.githubusercontent.com/assets/6840045/26751657/d54dd2b8-483e-11e7-9531-0b418f4aa2b2.png)

Same page, on the left there is the picker, on the right you can see the listbox rendered correcly ( without the color picker ), the blank field is intended.

**Comment by timcsy** [comment]
exactly the problem, and I'm using Chrome 58.0.3029.110 (64-bit), too

**Comment by notwaldorf** [comment]
Unfortunately, this makes sense :(
Since `paper-swatch-picker` uses `paper-listbox` for rendering, and needs to style, it needs to use one of its `@apply` mixins. These mixins are globally applied in the app, so this style is applied everywhere in the app...

**Comment by timcsy** [comment]
How about using custom style?

**Comment by jsilvermist** [comment]
@notwaldorf I don't understand this, shouldn't `@apply` or any mixins/variables be scoped to the stacking context by definition?

**Comment by microDimensions** [comment]
PR #24 should fix this issue.
