### ISSUE TITLE
Last row not rendered when column-count !=  tiles in the row

### ISSUE THREAD

**Issue by hitokiri8x** [PolymerElements/paper-swatch-picker#23]
### Description
Color tile row does not render correctly when row has not the same count as column-count property. 

### Expected outcome

The last row is rendered with the correct number of  tiles 

![exptected](https://cloud.githubusercontent.com/assets/6840045/26752191/8dc2b9f2-484a-11e7-89f9-222bf10cc118.png)

### Actual outcome

If you have column-count property set to 5 and 12 items, the last 2 items does not show.
It happens to 11 to 14 items. The last row to show MUST have a number of items equal to the colomn-count.
![picker](https://cloud.githubusercontent.com/assets/6840045/26752199/a34a2d6e-484a-11e7-9809-f27331b404d0.png)

### Steps to reproduce

``` 
<paper-swatch-picker column-count="5" color-list='["#65a5f2", "#2b63ba", "#83be54", "#3b8638", "#f0d551", "#d7be48","#65a5f2", "#2b63ba", "#83be54", "#3b8638", "#f0d551", "#d7be48"]'></paper-swatch-picker>
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [not tested] Safari 9
- [not tested] Safari 8
- [not tested] Safari 7
- [not tested] Edge
- [not tested] IE 11
- [not tested] IE 10

**Comment by eskan** [comment]
Hi @notwaldorf,
the layout have been set vertically so in fact to fill 12 colors in 5 columns is done with 4 it's done like this :
XXXX_
XXXX_
XXXX_
A solution could be to set a horizontal layout but this is a breaking change.
So the idea is to replace "empty columns with padding"
https://github.com/eskan/paper-swatch-picker/commit/fe8ed48992952cc253edd49701ebe55d5b7c2cfa

<img width="127" alt="capture d ecran 2017-10-20 a 13 58 44" src="https://user-images.githubusercontent.com/1148360/31820249-ca635c4a-b5a0-11e7-8753-debd6017aa6f.png">

Regards,

**Comment by jean-maxime** [comment]
Hello,

I'm facing the same problem.
Can't we do this in the attached function : 

`var rowCount = Math.round(this.colorList.length / this.columnCount);`

With this, we've got always the good height. For the width, the user has to be carefull with the 
 `columnCount` propertie

What do you think of it ?

**Comment by notwaldorf** [comment]
If that works and still looks fine, that'd be a good fix, i think!
