### ISSUE TITLE
Selected color chip changes after page refresh.

### ISSUE THREAD

**Issue by amanshu-kataria** [PolymerElements/paper-swatch-picker#26]
### Description
I'm using this component in my Polymer 2 application. I'm storing the selected color in the local storage. After I refresh the page, the selected color chip changes to the first color.

### Expected outcome

The selected color chip should remain the same even after refresh.

### Actual outcome

The selected color chip changes to the first color after refresh.

### Live Demo
Here's the [Codepen](https://codepen.io/amanshu_kataria/pen/WEoEmB) link.

### Browsers Affected
Tested only on Chrome as I'm developing Chrome extension.

**Comment by amanshu-kataria** [comment]
@notwaldorf need help here please.

**Comment by notwaldorf** [comment]
Not sure what's happening here. Maybe it's a race condition in your setup? One thing to do while debugging is try it without a `paper-swatch-picker` and using a different custom element instead, does it work then? 

`paper-swatch-picker` allows you to set or get a value as part of its api, and that works: http://jsbin.com/cihaqir/edit?html,output. This looks like it has nothing to do with this element, and with your app-storage setup instead.

**Comment by amanshu-kataria** [comment]
I'll check and let you know.
________________________________
