### ISSUE TITLE
Uncaught ReferenceError: KeyframeEffect is not defined

### ISSUE THREAD

**Issue by rawberg** [PolymerElements/paper-swatch-picker#36]
### Description
Clicking the bucket icon shows the palette and spits out an error to the console:
`Uncaught ReferenceError: KeyframeEffect is not defined`
Choosing a color does not make the palette go away or set the property bound to "color".

### Expected outcome
Palette should disappear and the value should be bound to the selected color value.

### Actual outcome
Palette remains open and there doesn't appear to be a way to dismiss it.

### Steps to reproduce
Add the element to the page and click the bucket icon.

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Environment Notes ###
"polymer": "2.3.1",
"paper-swatch-picker": "2.1.0"
"web-animations-js": "2.3.1" (happens with or without this)

"polymer-webpack-loader": "^2.0.1"

### Possibly Related Issues ###
Tried suggestions in all these, and was unable to resolve the issue.
[https://github.com/web-animations/web-animations-js/issues/45](https://github.com/web-animations/web-animations-js/issues/45)
[https://github.com/PolymerElements/paper-dropdown-menu/issues/242](https://github.com/PolymerElements/paper-dropdown-menu/issues/242)
[https://github.com/PolymerElements/paper-tooltip/issues/109](https://github.com/PolymerElements/paper-tooltip/issues/109)
[https://github.com/alchaplinsky/polymer-elements-rails/issues/1](https://github.com/alchaplinsky/polymer-elements-rails/issues/1)

Adding `web-animations-js/web-animations-next-lite.min.html`
results in the page not loading at all (blank white) and console showing `Uncaught TypeError: Cannot set property 'true' of undefined`. Attempting to shim it as [suggested here](https://github.com/web-animations/web-animations-js/issues/45#issuecomment-326398977) appears to have no affect.

**Comment by lastmjs** [comment]
Shouldn't it be `web-animations-js/web-animations-next-lite.min.js`?

**Comment by notwaldorf** [comment]
You need to import `neon-animation/web-animations.html` in your demo: http://jsbin.com/qomovig/edit?html,output

**Comment by rawberg** [comment]
For anyone else that stumbles into this. The fix that worked with webpack and babel was to exclude bower_components from being transpiled.

```
                enforce: "pre",
                test: /\.js$/,
                use: [
                    {loader: 'babel-loader'},
                ],
                exclude: /(node_modules\/(?!polymer-webpack-loader\/)|bower_components)/
```
Inspired by: https://github.com/aruntk/wc-loader/issues/12

**Comment by 8llouch** [comment]
[Neon-animation deprecated](https://www.webcomponents.org/element/PolymerElements/neon-animation)

Neon-animation is officialy deprecated (see above), aren't official component dependencies supposed to be updated ?? 

[Polymer blog](https://www.polymer-project.org/blog/2017-07-12-an-update-on-neon-animation)

"What should I do?
If you're creating a new element from scratch, we recommend using CSS keyframe animations, CSS transitions, or the Web Animations API.

**If you're using another element from the PolymerElements org that depends on neon-animation, like iron-dropdown or paper-menu-button, don't sweat it. We'll replace these animations.**

If you're using neon-animation directly, you should start planning to eventually move off it."

**Comment by 8llouch** [comment]
By the way, problem fixed by installing web-animation-js:
bower install web-animations-js --save

And we did import the dependency:
<link rel="import" href="../bower_components/web-animations-js/web-animations-next.min.html">

This works fine with <paper-swatch-picker> !

**Comment by arlimus** [comment]
Unfortunately the neon-animation solution didn't work for me. Updated @8llouch answer to Polymer3:

1. Install the package

    ```bash
    yarn add web-animations-js
    ```

2. Add this to your `index.html`

     ```html
     <script src="../node_modules/web-animations-js/web-animations-next.min.js"></script>
     ```

**Comment by andersforsell** [comment]
I'm running into this problem when migration to Polymer 3. 
The element .js file should have the needed dependencies so I tried @arlimus workaround, but instead of adding the dependency in the HTML I included an import in JS:
`import 'web-animations-js/web-animations-next.min.js';`

But that results in the following error: 

`scope.js:20 Uncaught TypeError: Cannot set property 'true' of undefined
    at VM4572 web-animations-next.min.js:2530
    at VM4572 web-animations-next.min.js:2531`

Any idea why?

**Comment by vers10ne** [comment]
@andersforsell ..     i did the same and got the same error.
maybe has to do with global scope, from the element it can't be 'seen'... but can be from index.html.

**Comment by rwrz** [comment]
@andersforsell I found the problem here... fixed after added this BEFORE webcomponents-loader.js
```
    <script src="node_modules/web-animations-js/web-animations-next-lite.min.js"></script>
```

**Comment by ericbaltha** [comment]
@rwrz I try to do the migration to Polymer 3 and I got the same error and this solution doesn't seem to be a reel solution cause it didn't work in my case. But maybe it's related with the importation cycle.

**Comment by grishick** [comment]
@ericbaltha same problem after migrating to Polymer 3.

**Comment by grishick** [comment]
@ericbaltha  I got it to work with Polymer 3. Here's what I had to do.
1. add "web-animations-js": "^2.3.1" to "dependencies" in package.json
2. add "node_modules/web-animations-js/*.js" to "extraDependencies" in polymer.json
3. include webanimations JavaScript in index.html by adding 
`<script src="node_modules/web-animations-js/web-animations.min.js"></script>`
after this
`<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>`
4. import web-animations-next-lite.min.js in my module:
`import 'web-animations-js/web-animations-next-lite.min.js';` after all polymer imports.

**Comment by punkratz312** [comment]
@grishick  your solution actually non of the above mentioned ones work for me, i tried all of them :(

**Comment by punkratz312** [comment]
After importing all possible web-animations the error changed: 

![image](https://user-images.githubusercontent.com/8830888/44339742-cefa1600-a482-11e8-8d34-db4365a39390.png)

![image](https://user-images.githubusercontent.com/8830888/44339751-d6b9ba80-a482-11e8-896b-1c9965d1e909.png)

**Comment by grishick** [comment]
@punkratz312 have you tried importing ONLY web-animations-lite?
Also, note that I had to include web-animations.min.js in index.html as well as import web-animations-js/web-animations-next-lite.min.js in my module

**Comment by jcanales** [comment]
Followed all the suggestions and still have the same error. any ideas?

**Comment by mmpowers** [comment]
For others' reference, the solution that worked for me was adding the script tag in the html: 
<script src="./node_modules/web-animations-js/web-animations-next-lite.min.js"></script>

**Comment by aneesshameed** [comment]
If you are here in 2019 and on polymer 3 then install web-animations-js from https://www.npmjs.com/package/web-animations-js and then in custom element file add below line
import 'web-animations-js/web-animations-next-lite.min.js'; If it is on html file add it via script tag.

**Comment by anoopsharma010395** [comment]
@aneesshameed  Cannot set property 'true' of undefined ERROR is comming after importing web-animations-js/web-animations-next-lite.min.js . Any idea how to resolve this.

**Comment by aneesshameed** [comment]
@anoopsharma010395 That doesn't looks like a polymer error.

**Comment by CookedApps** [comment]
In my case i was having this issue with Vaadin. I am using paper-swatch-picker version 2.3.1 and importing `../neon-animation/web-animations.html` solved the issue for me.

**Comment by guenoledc** [comment]
Hi, after struggling, I have made it work (Chrome 72 - not yet tested other versions/navigator)

1- add "web-animations-js": "^2.3.1" to "dependencies" in package.json
2- add "node_modules/web-animations-js/*.js" to "extraDependencies" in polymer.json (Not seen if usefull yet)
3- include webanimations JavaScript in index.html by adding
<script src="node_modules/web-animations-js/web-animations.min.js"></script>
AFTER THIS
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>


Nothing else (no other import in my module, except the following
import '@polymer/paper-dropdown-menu/paper-dropdown-menu.js';
import '@polymer/paper-item/paper-item.js';
import '@polymer/paper-listbox/paper-listbox.js';

thanks to @grishick
