### ISSUE TITLE
Colour property not respected

### ISSUE THREAD

**Issue by alodavide** [PolymerElements/paper-swatch-picker#37]
### Description
The `paper-swatch-picker` element does not take the colour parameter into account.

### Expected outcome
In the demo page (first example), the last button icon is supposed to be light blue.

### Actual outcome
The button is actually light red.

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-swatch-picker/demo/demo/index.html

### Steps to reproduce
1. Visit demo page.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jsilvermist** [comment]
Very strange, I just clicked on the Live Demo link and it showed up perfectly, then I closed and reopened the tab and started seeing the issue you described.
