### ISSUE TITLE
Missing Docs/Demo?

### ISSUE THREAD

**Issue by MoonDawg92** [PolymerElements/paper-swatch-picker#8]
Can we expect to see documentation and/or a demo for paper-swatch-picker anytime soon?

The page is currently blank: https://elements.polymer-project.org/elements/paper-swatch-picker

The bower install command is also undefined on the left hand side of the page.

**Comment by notwaldorf** [comment]
I think this is because the element is missing from the list of `paper-elements`: it's not actually navigatable from https://elements.polymer-project.org/browse?package=paper-elements.

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/paper-elements#73
