### ISSUE TITLE
No style works

### ISSUE THREAD

**Issue by gucantine** [PolymerElements/paper-swatch-picker#9]
### Description
We can't apply any style, and i search to use this style :  --paper-swatch-picker-icon

### Expected outcome
no effects with styles : 
--paper-swatch-picker-color-size	The size of each of the color boxes 	20px
--paper-swatch-picker-icon-size	The size of the color picker icon	        24px
--paper-swatch-picker-icon	        Mixin applied to the color picker icon	   {}

### Browsers Affected

- [*] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by trebormat** [comment]
I have the same issue with the style. It doesn't work for icon size (in demo code) and also for change the icon image (from icon-icon and icon-set)

**Comment by gucantine** [comment]
Anyone?

**Comment by gucantine** [comment]
up

**Comment by notwaldorf** [comment]
Are you using `style is="custom-style`? It seems that `--paper-swatch-picker-icon-size` is indeed unused, but here's a demo of the other properties and mixins working: http://jsbin.com/qaxidav/edit?html,output.

@trebormat Would you be interested in sending a PR to remove the unused property? If you can't, I can get to it this week :)
